config/routes.rb
Rails.application.routes.draw do
  root :to => 'home#index'

  get 'home' => 'home#index'
  get 'about' => 'home#about'
  get 'contact' => 'home#contact'
  get 'privacy' => 'home#privacy'
  get 'agreement' => 'home#agreement'

  # Kutorable specific routes
  get 'vote' => 'kutorable/voting#vote'
  get 'vote/reload' => 'kutorable/home#random_animal_picture'
  post 'signup' => 'kutorable/home#mailing_list_sign_up'
end

app/controllers/home_controller.rb
class HomeController < TrackedController
  def index
    client = Client.current.name.gsub "-", ""
    public_send "#{client}_index"
  end

  def about
  end

  def contact
  end

  def privacy
  end

  def agreement
  end

  def celebheadlines_index
    @headlines = CelebHeadline.all.order(:posted_at)
  end

  def kutorable_index
    ap_id = params['apid'].presence
    @picture = AnimalPicture.find_by_id(ap_id) || AnimalPicture.joins("LEFT JOIN animal_votes av ON av.animal_picture_id = animal_pictures.id AND av.arrival_id = #{current_arrival.id}")
        .where("av.id IS NULL")
        .order("rand()").first
    @current_arrival = current_arrival
    @source = @picture.try(:source) || "missing"
  end

  def panikmedia_index
  end
end

app/controllers/kutorable/home_controller.rb
class Kutorable::HomeController < TrackedController
  protect_from_forgery
  def random_animal_picture
    picture = AnimalPicture.joins("LEFT JOIN animal_votes av ON av.animal_picture_id = animal_pictures.id AND av.arrival_id = #{current_arrival.id}")
        .where("av.id IS NULL")
        .order("rand()").first
    if picture
      random_picture = {
        :id => picture.id,
        :file_name => picture.file_name,
        :voting_aggregate => picture.voting_aggregate,
        :source => picture.source,
        :source_url => picture.source_url,
      }
    else
      random_picture = {
        :id => 0,
        :file_name => "end_image.jpg",
        :voting_aggregate => nil,
        :source => nil,
        :source_url => nil,
      }
    end

    render :json => random_picture
  end

  def mailing_list_sign_up
    @email = Email.create :email => params[:email].presence,
                          :client_id => Client.current.id,
                          :arrival_id => current_arrival.id 
    render :text => "OK"
  end
end

app/controllers/kutorable/voting_controller.rb
class Kutorable::VotingController < UntrackedController
  def vote
    arrival_id = params[:aid].presence
    animal_picture_id = params[:apid].presence
    vote = params[:vote].presence

    if arrival_id && animal_picture_id && vote
      unless AnimalVote.find_by(:arrival_id => arrival_id, :animal_picture_id => animal_picture_id)
        aggregate = VotingAggregate.find_or_create_by(:animal_picture_id => animal_picture_id)
        case vote
        when 'cute'
          aggregate.cute_votes += 1
        when 'ugly'
          aggregate.ugly_votes += 1
        else
          return render :text => "Malformed Vote"
        end
        aggregate.save!

        AnimalVote.create :arrival_id => arrival_id,
                          :animal_picture_id => animal_picture_id,
                          :vote => vote

        return render :text => "OK"
      else
        return render :text => "Already Voted"
      end
    end

    render :text => "Blank Vote Data"

  end
end

app/views/kutorable/home/about.html.erb
<% provide :title, "About" %>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-12">
      <div class = "staticContainer">
        <h1>About</h1>
        <p>At Kutorable, we are aggregating all the 'kute' and 'adorable' (hence <i>Kutorable</i>, get it?) 
          pet pictures we find from both the internet and pet owners wanting to show off their pets.
          Vote the pictures that you see as "Kute" or "meh", and help us discover the <i>kutest</i>
          pets on the interwebs!</p>
          <p>Do you have a cute pet image that you want us to share? Mail it over to us at kutorable@gmail.com!</p>
      </div>
    </div>
  </div>
</div>

app/views/kutorable/home/agreement.html.erb
<% provide :title, "User Agreement" %>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-12">
      <div class = "staticContainer">
        <h1>User Agreement</h1>
        <p>We're all about <i>kute</i> animals and such, but we don't appreciate funny business. Here is our user agreement:</p>
          <p>1) Images that you provide us to host on our site is either your own, or you have permission for us to share. We 
              respect the original owners of their photos, and do not wish to post their images against their wishes. <br/>
             2) No questionable material. Please don't submit anything questionable, illegal, and irrelevant to our website. 
                <br/>
             3) You understand that your traffic on kutorable and all Panik Media websites is tracked. We don't track any private info,
             or do we intend to share any of your info to third parties. Check out our <a href="/privacy">Privacy Policy</a></p>
      </div>
    </div>
  </div>
</div>

app/views/kutorable/home/contact.html.erb
<% provide :title, "Contact" %>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-12">
      <div class = "staticContainer">
        <h1>Contact</h1>
        <p>Want to share your pet pictures with us? Have a question or concern? Email us at kutorable@gmail.com! Please make sure
            that pictures you send us are of pets/animals only. We love people too, but just not in our pictures.</p>
        <p>If you are the original owner of an image or know the original owner and our sources are not cited correctly, please let us know ASAP
          so we can give credit to the photographers of these awesome pictures.</p>
        <p>Be sure to check out our <a href = "http://www.twitter.com/kutorable" target = "_blank">Twitter</a> 
           and <a href = "https://www.facebook.com/pages/Kutorable/260954180774995?ref_type=bookmark" target="_blank">Facebook</a> pages for more pet pics.</p>
      </div>
    </div>
  </div>
</div>

app/views/kutorable/home/index.html.erb
<% provide :title, "" %>

<div id="content-container" class="container">
  <div class="row">
    <div class="voting_canvas">
      <div class = "image-cropper">
        <img id="animal_picture" src="../../assets/animal_pictures/<%= @picture.try(:file_name) || "end_image.jpg" %>"/>
      </div>
      <span id="imageSource">
        <% if @picture.try(:source_url) %>
          Source:  <%=link_to(@source, @picture.source_url, target: "_blank")%>
        <% else %>
          Source: MIA
        <% end %>
      </span>
      <div id="voting_container">
        <table class = "table votingTallies">
          <tbody>
            <tr>
              <td width="14%"><img class = "votingScoreImages"
                                    src="../../assets//kutorable/sadface.png"/> </td>
              <td id="ugly_votes" width="31%"><%= @picture.try(:voting_aggregate).try(:ugly_votes) || 0 %></td>
              <td width="10%">|</td>
              <td width="14%"><img class = "votingScoreImages"
                                    src="../../assets//kutorable/heart.png"/> </td>
              <td id="cute_votes" width="31%"><%= @picture.try(:voting_aggregate).try(:cute_votes) || 0 %></td>
            </tr>
          </tbody>
        </table>

        <ul class="nav nav-pills">
          <li id="mehVoteButton"><%= link_to("meh.", vote_path(:aid => @current_arrival.id, :apid => @picture.try(:id), :vote => "ugly"),
                  :remote => true, class: "reloadOnClick")%></li>
          <li id="cuteVoteButton"><%= link_to("AWW!", vote_path(:aid => @current_arrival.id, :apid => @picture.try(:id), :vote => "cute"),
                  :remote => true, class: "reloadOnClick")%></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/kutorable/home/privacy.html.erb
<% provide :title, "Privacy Policy" %>

<div class="container">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 col-xs-12">
      <div class = "staticContainer">
        <h1>Privacy Policy</h1>
        <p>At Kutorable, our goal is to find all the kute animal pictures out on the internet for your viewing pleasure. 
        	If you leave our site with your heart melted, our goal is accomplished. That being said, we still need to
        	go over our privacy policy.</p>
          <p>1) To our knowledge, all images on our site are either public domain, user submitted, or free to use. If you are 
          	the owner of an image and wish for us to remove it from our site (but why would you want to do that??), email us
          	at kutorable@gmail.com and we will address it promptly. <br/>
          	2) We monitor traffic. Just a heads up, we do monitor your traffic ONLY within OUR site and websites in the Panik 
          	Media network. We have no intentions of providing this information with a third party.
          	</p>
      </div>
    </div>
  </div>
</div>